language: node_js
sudo: false
cache: false
branches:
  only:
  - master
script:
- npm run lint
- npm run build
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
