language: node_js
sudo: false
cache: false
branches:
  only:
  - master
script:
- npm run lint
- npm test
- npm run build:releases
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
